### PR TITLE
fix: update pdfreader to work with pdfplumber >  v0.11.5

### PR DESCRIPTION
**Pull request by sebusch**
fixes TypeError: PageImage.debug_tablefinder() got an unexpected keyword argument 'tf'

### CODE REVIEW

**Comment by redstreet** [comment]
Thank you for this fix!
